draw_sprite(spr_yaysuulifeicon, 0, 0, 0)
draw_sprite(spr_teddylifeicon, 0, 0, 32)
if (global.char == "Y")
	draw_sprite(spr_pizza, 0, 32, 0)
else if (global.char == "T")
	draw_sprite(spr_pizza, 0, 32, 32)

draw_set_halign(fa_center)
draw_set_font(global.smalloptfont)
draw_text(320, 240, string(selection))
draw_text(320, 416, "use movement keys to switch selection")
draw_set_font(global.font)
draw_text(320, 256, optiontext)
draw_set_halign(fa_left)