/// @description Insert description here
// You can write your code in this editor
draw_set_valign(fa_top)
draw_set_font(global.font)
draw_text(32, 16*02, "CREDITS")
draw_set_font(global.subtitlefont)
draw_text_yxa(32, 16*04, "YAYSUU (Programmer, Artist, Composer)", "white", true)
draw_text_yxa(32, 16*05, "JarekTEK (Composer)", "white", true)
draw_text_yxa(32, 16*06, "Fazmade (Programmer, Minor Artist)", "white", true)
draw_text_yxa(32, 16*07, "TeddyP (Voice Actor, Brother)", "white", true)
draw_set_font(global.font)
draw_text(32, 16*08, "SPECIAL THANKS")
draw_set_font(global.subtitlefont)
draw_text_yxa(32, 16*10, "Robert (SH2K) (UCG Creator)", "white", true)
draw_text_yxa(32, 16*11, "SwackyGCF (Guest Character Designer)", "white", true)
draw_text_yxa(32, 16*12, "Midi Bradford (Intro Logo Editing)", "white", true)
draw_text_yxa(32, 16*13, "Onsku `s`cg(Scripting Help)", "white", true)
draw_set_font(global.font)
draw_text(32, 16*14, "PLAYTESTERS")
draw_set_font(global.subtitlefont)
draw_text_yxa(32, 16*16, "Tay      JarekTEK Nelson  hifish", "white", true)
draw_text_yxa(32, 16*17, "Kola     Teddy    Idaho   LazerBoi", "white", true)
draw_text_yxa(32, 16*18, "Midi     Fazmade  Aiden50yes", "white", true)
draw_text_yxa(32, 16*19, "SirCub   Janknee  Yoshi", "white", true)