// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function settings_init(){
	ini_open("savedata.ini")
	// SETTINGS SAVEDATA INITIALIZATION
	audio_master_gain(ini_read_real("settings","volume",1))
	global.musvol=ini_read_real("settings","musvol",1)
	global.sndvol=ini_read_real("settings","sndvol",1)
	global.voicelines=ini_read_real("settings","voicelines",true)
	global.sensitivity=ini_read_real("settings","sensitivity",0.35) // actually deadzone but not gonna change the variable name now
	global.controlalpha=ini_read_real("settings","controlalpha",0.5)
	global.controldistance=ini_read_real("settings","controldistance",0)
	window_set_fullscreen(ini_read_real("settings","fullscreen",false))
	global.screenshake=ini_read_real("settings","screenshake",true)
	global.borders=ini_read_real("settings","borders",true)
	global.keytype=ini_read_real("settings","keytype",-1)
	global.speedrun=ini_read_real("settings","speedrun",false)
	global.screenscale=ini_read_real("settings","screenscale",1)
	// P1 CONTROLS SAVEDATA INITIALIZATION
	global.p1_controlslot=ini_read_real("controls","p1controlslot",0)
	global.p1_leftkey=ini_read_real("controls","p1leftkey",vk_left)
	global.p1_rightkey=ini_read_real("controls","p1rightkey",vk_right)
	global.p1_upkey=ini_read_real("controls","p1upkey",vk_up)
	global.p1_downkey=ini_read_real("controls","p1downkey",vk_down)
	global.p1_jumpkey=ini_read_real("controls","p1jumpkey",ord("Z"))
	global.p1_dashkey=ini_read_real("controls","p1dashkey",ord("X"))
	global.p1_runkey=ini_read_real("controls","p1runkey",ord("C"))
	global.p1_startkey=ini_read_real("controls","p1startkey",vk_enter)
	global.p1_autorun=ini_read_real("controls","autorun",true)
	global.menubuttontype=ini_read_real("controls","menubuttontype",false)
	global.vibration=ini_read_real("controls","vibration",true)
	// P2 CONTROLS SAVEDATA INITIALIZATION
	global.p2_controlslot=ini_read_real("controls","p2controlslot",1)
	global.p2_leftkey=ini_read_real("controls","p2leftkey",ord("J"))
	global.p2_rightkey=ini_read_real("controls","p2rightkey",ord("L"))
	global.p2_upkey=ini_read_real("controls","p2upkey",ord("I"))
	global.p2_downkey=ini_read_real("controls","p2downkey",ord("K"))
	global.p2_jumpkey=ini_read_real("controls","p2jumpkey",ord("O"))
	global.p2_dashkey=ini_read_real("controls","p2dashkey",ord("P"))
	global.p2_runkey=ini_read_real("controls","p2runkey",ord("U"))
	global.p2_startkey=ini_read_real("controls","p2startkey",ord("Y"))
	global.p2_autorun=ini_read_real("controls","p2autorun",true)
	ini_close()
	window_set_size(640*global.screenscale,480*global.screenscale)
	display_set_gui_size(640,480)
}