/// @description initial variables
// You can write your code in this editor
hsp = 0 // horizontal speed
vsp = 0 // vertical speed
grv = 0.3 // gravity
jmp = -7 // jump strength
djmp = -8.4 //doublejump
fjmp = -5 //float jump?
wbop = -3.5 //water bop
wjmp = -5 //water jump strength
wdjmp = -4 //water double just
wallbump = -12 //wall jump boost
wsp = 4 //current walkspeed
djump = true // double jumped
dshed = false // airdashed
walkspeed = 4 // max speed
runspeed = 8.5
rundamagespeed = -0
bounceheight = -10
bounceheightbigger = -10
normalgrav = 0.3
stompgrav = 1
floatgrav = 0.1
watergrav = 0.15
vulnerable = true
winning = false
hurtt = 0; // hurt timer
sprite_index = spr_yaysuu_idle
global.inv=0
global.hp=3
grounded = true
prevgrounded = true
checkscale = 0.1
mask_index = spr_collisionmask
maxloop = 320
state = playerstates.normal
newstate = playerstates.normal
yearnedhsp = 0
yearnaccel = 0.5
yearnacceloverspeed = 0.05
yearnaccelunderspeed = 1
dashboost = 20
airdashboost = -0
idletime = 0
move = 0
facingdirection = 1
ouchies = false
rainbowtimer = 0
runningsound = audio_play_sound(snd_run, 1, true)
audio_pause_sound(runningsound)
hasplayedbrakesound = false
deathies = false
maxfallspeed = 10
smashbump = -0
runanimtimer = -1
hascollision = true
normmaxfall = 10
stompmaxfall = 15
floatmaxfall = 5
whooshcolor = #FFF1E8
slopey = false
prevslopey = false
showarrow = false
inbackground = false
damageflash = false
inwater = false
hangglidedir = 1
whichcollisionsdid = ""
hitboxcolor = c_lime
selecteddebugobject = 0
previousspawnedobject = noone
visualrotation = 0
lastwall = 0
key_left=false
key_leftp=false
key_right=false
key_rightp=false
key_down=false
key_downp=false
key_up=false
key_upp=false
key_jump=false
key_jumpp=false
key_dash=false
key_dashp=false
key_run=false
key_runp=false
offscreentimer=0
fratricide=false
isotherplayer = instance_number(obj_player) > 1
issecondplayer = isotherplayer // This is for CONTROLS ONLY.
char=isotherplayer ? global.p2char : global.char
if (global.p2char == global.char)
	scr_setupcharacter(char, 1)
else
	scr_setupcharacter(char, 0)